"""Initial schema: customers, scores, accounts, inquiries, collections, public_records

Revision ID: fe08a3da6d37
Revises: 
Create Date: 2026-07-25 17:58:29.990424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe08a3da6d37'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('pan_card', sa.String(length=10), nullable=False),
    sa.Column('customer_id', sa.String(length=50), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('dob_year', sa.Integer(), nullable=False),
    sa.Column('income_bracket', sa.String(length=50), nullable=False),
    sa.Column('income_monthly_paise', sa.Integer(), nullable=False),
    sa.Column('region', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('pan_card')
    )
    op.create_index(op.f('ix_customers_customer_id'), 'customers', ['customer_id'], unique=True)
    op.create_table('accounts',
    sa.Column('account_id', sa.String(length=50), nullable=False),
    sa.Column('pan_card', sa.String(length=10), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('account_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('balance_paise', sa.Integer(), nullable=False),
    sa.Column('credit_limit_paise', sa.Integer(), nullable=True),
    sa.Column('monthly_payment_paise', sa.Integer(), nullable=False),
    sa.Column('opened_date', sa.Date(), nullable=False),
    sa.Column('is_revolving', sa.Boolean(), nullable=False),
    sa.Column('payment_history', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pan_card'], ['customers.pan_card'], ),
    sa.PrimaryKeyConstraint('account_id')
    )
    op.create_index(op.f('ix_accounts_pan_card'), 'accounts', ['pan_card'], unique=False)
    op.create_table('collections',
    sa.Column('collection_id', sa.String(length=50), nullable=False),
    sa.Column('pan_card', sa.String(length=10), nullable=False),
    sa.Column('original_creditor', sa.String(length=255), nullable=False),
    sa.Column('collection_agency', sa.String(length=255), nullable=True),
    sa.Column('balance_paise', sa.Integer(), nullable=False),
    sa.Column('opened_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('is_past_sol', sa.Boolean(), nullable=False),
    sa.Column('is_disputable', sa.Boolean(), nullable=False),
    sa.Column('is_medical', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pan_card'], ['customers.pan_card'], ),
    sa.PrimaryKeyConstraint('collection_id')
    )
    op.create_index(op.f('ix_collections_pan_card'), 'collections', ['pan_card'], unique=False)
    op.create_table('inquiries',
    sa.Column('inquiry_id', sa.String(length=50), nullable=False),
    sa.Column('pan_card', sa.String(length=10), nullable=False),
    sa.Column('creditor_name', sa.String(length=255), nullable=False),
    sa.Column('inquiry_date', sa.Date(), nullable=False),
    sa.Column('inquiry_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pan_card'], ['customers.pan_card'], ),
    sa.PrimaryKeyConstraint('inquiry_id')
    )
    op.create_index(op.f('ix_inquiries_pan_card'), 'inquiries', ['pan_card'], unique=False)
    op.create_table('public_records',
    sa.Column('record_id', sa.String(length=50), nullable=False),
    sa.Column('pan_card', sa.String(length=10), nullable=False),
    sa.Column('record_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('amount_paise', sa.Integer(), nullable=True),
    sa.Column('jurisdiction', sa.String(length=255), nullable=True),
    sa.Column('filed_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pan_card'], ['customers.pan_card'], ),
    sa.PrimaryKeyConstraint('record_id')
    )
    op.create_index(op.f('ix_public_records_pan_card'), 'public_records', ['pan_card'], unique=False)
    op.create_table('scores',
    sa.Column('score_id', sa.Integer(), nullable=False),
    sa.Column('pan_card', sa.String(length=10), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('band', sa.String(length=50), nullable=False),
    sa.Column('score_as_of_date', sa.Date(), nullable=False),
    sa.Column('previous_score_1mo', sa.Integer(), nullable=True),
    sa.Column('previous_score_3mo', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pan_card'], ['customers.pan_card'], ),
    sa.PrimaryKeyConstraint('score_id')
    )
    op.create_index(op.f('ix_scores_pan_card'), 'scores', ['pan_card'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scores_pan_card'), table_name='scores')
    op.drop_table('scores')
    op.drop_index(op.f('ix_public_records_pan_card'), table_name='public_records')
    op.drop_table('public_records')
    op.drop_index(op.f('ix_inquiries_pan_card'), table_name='inquiries')
    op.drop_table('inquiries')
    op.drop_index(op.f('ix_collections_pan_card'), table_name='collections')
    op.drop_table('collections')
    op.drop_index(op.f('ix_accounts_pan_card'), table_name='accounts')
    op.drop_table('accounts')
    op.drop_index(op.f('ix_customers_customer_id'), table_name='customers')
    op.drop_table('customers')
    # ### end Alembic commands ###
