#!/usr/bin/env python3
"""Build the chat RAG index and guardrail example bank.

Reads ``app.kb_loader.get_knowledge_base()`` (32 labels) and the curated
in-scope / out-of-scope example bank and writes two deterministic Python
modules:

* ``app/chat_kb_data.py``       — bundled chunk vectors + label sources map.
* ``app/chat_guardrail_data.py`` — embedded guardrail example vectors.

Both artifacts are committed to the repo so Vercel never embeds at deploy
time (the scripts/ tree is excluded from the function bundle).

Usage:
    export OPENAI_API_KEY=...
    python scripts/build_chat_kb.py             # write both modules
    python scripts/build_chat_kb.py --check     # exit 1 if either is stale
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Iterable, Sequence

PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PROJECT_ROOT))

from app.config import LABEL_KB_PATH  # noqa: E402
from app.kb_loader import KBEntry, KnowledgeBase, get_knowledge_base  # noqa: E402

EMBEDDING_MODEL = "text-embedding-3-small"
EMBEDDING_DIM = 1536

CHUNK_OUT = PROJECT_ROOT / "app" / "chat_kb_data.py"
GUARD_OUT = PROJECT_ROOT / "app" / "chat_guardrail_data.py"

IN_SCOPE_EXAMPLES: tuple[str, ...] = (
    "what is rate shopping",
    "should I close my oldest credit card",
    "how long does a late payment stay on my CIBIL report",
    "what is a good credit utilization ratio",
    "how do I improve my CIBIL score",
    "should I pay off my credit card",
    "how long do hard inquiries stay on the report",
    "what does maxed out mean for my score",
)

OUT_OF_SCOPE_EXAMPLES: tuple[str, ...] = (
    "should I invest in index funds",
    "what career should I pursue",
    "should I rent or buy a house",
    "how should I plan my taxes",
    "what stocks should I buy",
    "should I start my own business",
    "is it a good time to switch jobs",
    "what is the best SIP to start",
)


CHUNK_TEXT_TEMPLATE = (
    "{display_name} ({category}, {severity}, priority {priority}). "
    "{condition_human} {what_it_means_cibil} {why_it_matters} "
    "Mitigation: {mitigation}"
)

HEADER_COMMENT = (
    "Auto-generated by scripts/build_chat_kb.py. Do not edit."
)

_SAFE_REPR_CHARS_TO_ESCAPE = re.compile(r"['\"\\]")


def _escape_repr(text: str) -> str:
    """Quote a chunk text safely for ``repr()`` output."""
    return repr(text)


def _chunk_text(entry: KBEntry) -> str:
    mitigation = "; ".join(entry.mitigation_steps)
    return CHUNK_TEXT_TEMPLATE.format(
        display_name=entry.display_name,
        category=entry.category.value,
        severity=entry.severity.value,
        priority=entry.priority_rank,
        condition_human=entry.condition_human,
        what_it_means_cibil=entry.what_it_means_cibil,
        why_it_matters=entry.why_it_matters,
        mitigation=mitigation or "(none)",
    )


def _kb_sorted(kb: KnowledgeBase) -> list[KBEntry]:
    """Sort entries deterministically: priority_rank ASC, label_id ASC."""
    return sorted(kb.all_entries(), key=lambda entry: (entry.priority_rank, entry.label_id))


def _kb_payload_signature(entries: Sequence[KBEntry]) -> str:
    """Stable digest of the KB content for staleness detection."""
    material: list[dict] = []
    for entry in entries:
        material.append(
            {
                "label_id": entry.label_id,
                "display_name": entry.display_name,
                "condition_human": entry.condition_human,
                "what_it_means_cibil": entry.what_it_means_cibil,
                "why_it_matters": entry.why_it_matters,
                "mitigation_steps": list(entry.mitigation_steps),
                "sources": [(s.title, s.url) for s in entry.sources],
                "priority_rank": entry.priority_rank,
                "category": entry.category.value,
                "severity": entry.severity.value,
            }
        )
    payload = json.dumps(material, sort_keys=True, ensure_ascii=False)
    return hashlib.sha256(payload.encode("utf-8")).hexdigest()


def _l2_normalize(vec: Sequence[float]) -> list[float]:
    """Local mirror of the runtime normalization (rounded to 4 decimals)."""
    norm = sum(x * x for x in vec) ** 0.5
    if norm == 0:
        raise ValueError("zero-magnitude embedding")
    return [round(x / norm, 4) for x in vec]


def _format_vector(vec: Sequence[float]) -> str:
    """Render a vector as ``(0.1234, -0.5678, ...)``.

    Fixed ``.4f`` formatting keeps the emitted module byte-stable across
    runs on the same input.
    """
    parts = [f"{x:.4f}" for x in vec]
    return "(" + ", ".join(parts) + ")"


def _format_sources(sources: Iterable) -> list[tuple[str, str]]:
    return [(s.title, s.url) for s in sources]


def _write_module(
    path: Path,
    header_lines: list[str],
    body: str,
) -> None:
    text = "\n".join(header_lines) + "\n\n" + body + "\n"
    if not text.endswith("\n"):
        text += "\n"
    path.write_text(text, encoding="utf-8")


def _build_chunk_module(
    entries: Sequence[KBEntry],
    vectors: Sequence[Sequence[float]],
    *,
    generated_at: str,
    digest: str,
) -> None:
    if len(entries) != len(vectors):
        raise ValueError("entry/vector count mismatch")
    if vectors and len(vectors[0]) != EMBEDDING_DIM:
        raise ValueError(
            f"vectors have dimension {len(vectors[0])}, expected {EMBEDDING_DIM}"
        )

    lines: list[str] = [
        "from __future__ import annotations",
        "from typing import NamedTuple",
        "",
        f"EMBEDDING_MODEL = {EMBEDDING_MODEL!r}",
        f"EMBEDDING_DIM = {EMBEDDING_DIM}",
        f"SOURCE_DIGEST = {digest!r}",
        f"GENERATED_AT = {generated_at!r}",
        "",
        "class Chunk(NamedTuple):",
        "    label_id: str",
        "    text: str",
        f"    vector: tuple  # tuple[float, ...], {EMBEDDING_DIM} floats, L2-normalized",
        "",
        f"CHUNKS: tuple[Chunk, ...] = (",
    ]

    for entry, raw_vec in zip(entries, vectors):
        vec = _l2_normalize(raw_vec)
        text = _chunk_text(entry)
        lines.append(
            "    Chunk("
            f"{entry.label_id!r}, "
            f"{_escape_repr(text)}, "
            f"{_format_vector(vec)}"
            "),"
        )
    lines.append(")")
    lines.append("")

    lines.append("LABEL_SOURCES: dict[str, list[tuple[str, str]]] = {")
    for entry in entries:
        sources = _format_sources(entry.sources)
        if not sources:
            lines.append(f"    {entry.label_id!r}: [],")
            continue
        rendered = ", ".join(f"({title!r}, {url!r})" for title, url in sources)
        lines.append(f"    {entry.label_id!r}: [{rendered}],")
    lines.append("}")
    lines.append("")

    body = "\n".join(lines)
    _write_module(
        CHUNK_OUT,
        [f'"""{HEADER_COMMENT}"""'],
        body,
    )


def _build_guardrail_module(
    in_vectors: Sequence[Sequence[float]],
    out_vectors: Sequence[Sequence[float]],
    *,
    generated_at: str,
    digest: str,
) -> None:
    if in_vectors and len(in_vectors[0]) != EMBEDDING_DIM:
        raise ValueError("guardrail vectors have wrong dimension")

    lines: list[str] = [
        "from __future__ import annotations",
        "",
        f"EMBEDDING_MODEL = {EMBEDDING_MODEL!r}",
        f"EMBEDDING_DIM = {EMBEDDING_DIM}",
        f"SOURCE_DIGEST = {digest!r}",
        f"GENERATED_AT = {generated_at!r}",
        "",
        "IN_VECTORS: tuple[tuple[float, ...], ...] = (",
    ]
    for vec in in_vectors:
        lines.append(f"    {_format_vector(vec)},")
    lines.append(")")
    lines.append("")

    lines.append("OUT_VECTORS: tuple[tuple[float, ...], ...] = (")
    for vec in out_vectors:
        lines.append(f"    {_format_vector(vec)},")
    lines.append(")")
    lines.append("")

    body = "\n".join(lines)
    _write_module(
        GUARD_OUT,
        [f'"""{HEADER_COMMENT}"""'],
        body,
    )


def _embed_batch(embedder, texts: Sequence[str]) -> list[list[float]]:
    """Wrapper that runs the embedder with retry-on-transient-error."""
    import asyncio

    return asyncio.run(embed_batch_async(embedder, texts))


async def embed_batch_async(embedder, texts: Sequence[str]) -> list[list[float]]:
    results = await embedder.embed_batch(list(texts))
    return [list(v) for v in results]


def _write_manifest(
    entries: Sequence[KBEntry],
    in_examples: Sequence[str],
    out_examples: Sequence[str],
) -> str:
    return json.dumps(
        {
            "kb_count": len(entries),
            "in_count": len(in_examples),
            "out_count": len(out_examples),
            "first_label_id": entries[0].label_id if entries else None,
        },
        indent=2,
    )


def build(*, embedder_factory) -> dict:
    """Build both artifact modules. Returns a small summary dict.

    ``embedder_factory`` is a zero-arg callable that returns an ``Embedder``
    so tests can inject a fake without touching the OpenAI SDK.
    """
    kb = get_knowledge_base()
    entries = _kb_sorted(kb)
    if len(entries) != 32:
        raise SystemExit(
            f"Expected 32 KB labels, got {len(entries)}. "
            "Did scripts/seed_kb.py run?"
        )

    digest = _kb_payload_signature(entries)
    chunk_texts = [_chunk_text(entry) for entry in entries]

    embedder = embedder_factory()

    chunk_vectors = _embed_batch(embedder, chunk_texts)
    in_vectors = _embed_batch(embedder, list(IN_SCOPE_EXAMPLES))
    out_vectors = _embed_batch(embedder, list(OUT_OF_SCOPE_EXAMPLES))

    generated_at = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")

    _build_chunk_module(entries, chunk_vectors, generated_at=generated_at, digest=digest)
    _build_guardrail_module(
        in_vectors,
        out_vectors,
        generated_at=generated_at,
        digest=digest,
    )

    return {
        "kb_count": len(entries),
        "in_count": len(IN_SCOPE_EXAMPLES),
        "out_count": len(OUT_OF_SCOPE_EXAMPLES),
        "first_label_id": entries[0].label_id,
        "generated_at": generated_at,
        "digest": digest,
    }


def _existing_digest(path: Path) -> str | None:
    if not path.exists():
        return None
    text = path.read_text(encoding="utf-8")
    match = re.search(r'^SOURCE_DIGEST\s*=\s*"([0-9a-f]{64})"', text, re.MULTILINE)
    return match.group(1) if match else None


def _check_only() -> int:
    """Return 1 if either artifact is stale against the current KB; 0 otherwise."""
    kb = get_knowledge_base()
    entries = _kb_sorted(kb)
    fresh = _kb_payload_signature(entries)
    chunk_digest = _existing_digest(CHUNK_OUT)
    guard_digest = _existing_digest(GUARD_OUT)
    if chunk_digest != fresh:
        print(
            f"stale: chat_kb_data.py (digest {chunk_digest} != {fresh})",
            file=sys.stderr,
        )
        return 1
    if guard_digest != fresh and guard_digest is not None:
        print(
            f"stale: chat_guardrail_data.py (digest {guard_digest} != {fresh})",
            file=sys.stderr,
        )
        return 1
    return 0


def _embedder_factory_default():
    from app.embeddings import Embedder

    if not _check_env():
        raise SystemExit("OPENAI_API_KEY is required to build the chat index")
    return Embedder()


def _check_env() -> str | None:
    import os

    return os.getenv("OPENAI_API_KEY")


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Validate the on-disk artifacts against the live KB; exit 1 if stale.",
    )
    args = parser.parse_args(argv)

    if args.check:
        return _check_only()

    summary = build(embedder_factory=_embedder_factory_default)
    print(json.dumps(summary, indent=2))
    print(
        "\nWrote {kb} chunks + {in} in-scope + {out} out-of-scope examples to "
        "app/chat_kb_data.py and app/chat_guardrail_data.py".format(**summary),
        flush=True,
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
